#!/usr/bin/env bash
#xcape -e 'Caps_Lock=Escape' -t 180
#setxkbmap -option 'caps:ctrl_modifier' -layout "se" -variant "nodeadkeys"

setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'

#xcape -e 'Caps_Lock=Escape;Control_L=Escape;Control_R=Escape'
